spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authserver
    username: "<username>"
    password: "<password>"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:
        format_sql: true 
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
secret:
  token:
    refresh: "<refresh secret>"
    access: "<access secret>"
token:
  issuer: "<issuer>"